CREATE TABLE IF NOT EXISTS artists(
	id INT NOT NULL AUTO_INCREMENT,
	genre_id int NOT NULL,
	name VARCHAR(100) NOT NULL,
	birth_date DATE,
	description TEXT,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	
	PRIMARY KEY(id),
	CONSTRAINT FK_genre FOREIGN KEY (genre_id) REFERENCES genres(id)
);