CREATE TABLE IF NOT EXISTS albums(
	id int NOT NULL AUTO_INCREMENT,
	artist_id INT NOT NULL,
	name VARCHAR(100) NOT NULL,
	release_date DATE,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	
	PRIMARY KEY(id),
	CONSTRAINT FK_artist_album FOREIGN KEY(artist_id) REFERENCES artists(id)
);