CREATE TABLE IF NOT EXISTS songs(
	id INT NOT NULL AUTO_INCREMENT,
	album_id int  not null,
	name varchar(100) NOT NULL,
	duration int,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	
	PRIMARY KEY(id),
	CONSTRAINT FK_album_songs FOREIGN KEY (album_id) REFERENCES albums (id)
);